# app/config/routing.yml

# ...

security_login_form:
    path:   /login
    defaults:  { _controller: UsersBundle:Security:login }

security_login_check:
    path:   /login_check

security_logout:
    path:   /logout

users:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /
#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation