# app/config/security.yml

security:
    encoders:
        UsersBundle\Entity\Users: sha512
        UsersBundle\Entity\MyUsers:
            id: users.sha1_encoder

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        database_users:
            entity: { class: UsersBundle:Users, property: username }
        database_my_users:
            entity: { class: UsersBundle:MyUsers, property: login }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern:   ^/login$
            anonymous: true
        main:
            pattern:   ^/
            anonymous: false
            provider:  database_my_users
            form_login:
                login_path: security_login_form
                check_path: security_login_check
                default_target_path: users_home
                always_use_default_target_path: true
            logout:
                path:   security_logout
                target: /

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
