services:
    users.sha1_encoder:
        class: UsersBundle\Service\Sha1Encoder
#    user.example:
#        class: UsersBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
